-- CreateTable
CREATE TABLE "Ammo" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "ammo_turret" INTEGER NOT NULL,
    "id_user" INTEGER NOT NULL,
    CONSTRAINT "Ammo_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
